version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro
    image: postgres:latest
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:9.0.2
    environment:
      #DB_VENDOR: POSTGRES
      #DB_ADDR: postgres
      #DB_DATABASE: keycloak
      #DB_USER: ${POSTGRES_USER}
      #DB_SCHEMA: public
      #DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8080:8080"